### ISSUE TITLE
Is it realistic to move implemention to JS itself?

### ISSUE THREAD

**Issue by tlindener** [marvinroger/node-rcswitch#1]
Hi,

I'm relatively new to NodeJS and I'm thinking it might be interesting to reimplement the rc-switch functionality in Javascript directly (based on wiringPi). Do you think this is a realistic approach?

**Comment by marvinroger** [comment]
Hi,

This is perfectly realistic, and it [already exists](https://github.com/tjanson/PiSwitch). Because of that, this module will continue to be a native binding, so that developers can have the choice.

The only advantage I see to the pure JS approach is that the install time is faster (no compile-time), but at run-time it is slower. The difference is unnoticeable, though.
